import {useEffect,useState,type FormEvent} from "react";
import {apiClient,type PagedData} from "../../services/apiClient";
import {Button} from "../../components/ui/Button";
export type StockSku = {id:string;code:string;name:string;hsnSac:string;unitOfMeasure:string;quantity:number;inventoryValue:number;isActive?:boolean};
type Choice={id:string;name:string;cgst?:number;sgst?:number};
type Purchase={id:string;billNumber:string;description:string;quantity:number;date:string};
const field="rounded border bg-transparent p-2 text-sm";
export function SkuInventoryPanel({onChanged}:{onChanged:()=>void}) {
 const [skus,setSkus]=useState<StockSku[]>([]),[vendors,setVendors]=useState<Choice[]>([]),[taxes,setTaxes]=useState<Choice[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]);
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function refresh(){setSkus(await apiClient.get<StockSku[]>("/inventory/skus"));setPurchases(await apiClient.get<Purchase[]>("/inventory/skus/purchases"));}
 useEffect(()=>{void refresh().catch(e=>setError(String(e)));void Promise.all([apiClient.get<PagedData<Choice>>("/vendors?pageSize=100"),apiClient.get<PagedData<Choice>>("/taxes?pageSize=100")]).then(([v,t])=>{setVendors(v.items);setTaxes(t.items);}).catch(e=>setError(String(e)));},[]);
 const submit=(action:string)=>async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const d=new FormData(form);setBusy(true);setError("");
 try {
 if(action==="create") await apiClient.post("/inventory/skus",{code:d.get("code"),name:d.get("name"),hsnSac:d.get("hsn"),unitOfMeasure:d.get("unit")});
 if(action==="opening") await apiClient.post("/inventory/skus/opening-stock",{skuId:d.get("sku"),date:d.get("date"),quantity:Number(d.get("qty")),unitCost:Number(d.get("cost"))});
 if(action==="receive") await apiClient.post("/inventory/skus/receipts",{skuId:d.get("sku"),vendorId:d.get("vendor"),billNumber:d.get("bill"),date:d.get("date"),quantity:Number(d.get("qty")),unitCost:Number(d.get("cost")),paymentTermsDays:Number(d.get("terms")),taxId:d.get("tax")||null,interState:d.get("interstate")==="on"});
 if(action==="writeoff") await apiClient.post("/inventory/skus/write-off",{skuId:d.get("sku"),date:d.get("date"),quantity:Number(d.get("qty")),reason:d.get("reason")});
 if(action==="return") await apiClient.post("/accounting/corrections",{kind:"Purchase",sourceId:d.get("purchase"),noteDate:d.get("date"),reason:d.get("reason"),disposition:"Supplier"});
 await refresh();onChanged();form.reset();
 }catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const skuSelect=<select name="sku" aria-label="Stock SKU" className={field} required><option value="">Choose SKU</option>{skus.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name} · {s.quantity} {s.unitOfMeasure}</option>)}</select>;
 const date=<input aria-label="Stock date" className={field} name="date" type="date" required defaultValue={new Date().toLocaleDateString("en-CA")}/>;
 const qty=<input aria-label="Stock quantity" className={field} name="qty" type="number" min="0.0001" step="0.0001" required placeholder="Quantity"/>;
 return <section className="space-y-4 rounded border p-4"><h2 className="font-semibold">Accessory SKU inventory</h2><p className="text-sm">Stock uses moving average cost. Enter purchases and movements chronologically. Pay supplier bills from Purchase accounting; record refunds from Returns & Corrections.</p>
 {error&&<p role="alert" className="text-red-600">{error}</p>}
 <form onSubmit={submit("create")} className="flex flex-wrap gap-2"><input aria-label="SKU code" className={field} name="code" maxLength={40} required placeholder="SKU code"/><input aria-label="SKU name" className={field} name="name" maxLength={200} required placeholder="Accessory name"/><input aria-label="SKU HSN" className={field} name="hsn" pattern="([0-9]{4}|[0-9]{6}|[0-9]{8})" required placeholder="HSN"/><input aria-label="SKU unit" className={field} name="unit" maxLength={10} required defaultValue="NOS"/><Button type="submit" disabled={busy}>Create SKU</Button></form>
 <form onSubmit={submit("receive")} className="flex flex-wrap gap-2">{skuSelect}<select aria-label="SKU supplier" name="vendor" className={field} required><option value="">Supplier</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><input aria-label="Supplier bill" className={field} name="bill" maxLength={100} required placeholder="Supplier bill"/>{date}{qty}<input aria-label="SKU unit cost" className={field} name="cost" type="number" min="0" step="0.01" required placeholder="Tax-exclusive unit cost"/><input aria-label="Payment terms days" className={field} name="terms" type="number" min="0" max="3650" defaultValue="0"/><select aria-label="Purchase GST rate" name="tax" className={field}><option value="">No GST</option>{taxes.map(t=><option key={t.id} value={t.id}>{t.cgst}% + {t.sgst}%</option>)}</select><label><input name="interstate" type="checkbox"/> Interstate purchase (IGST)</label><Button type="submit" disabled={busy}>Receive stock</Button></form>
 <form onSubmit={submit("opening")} className="flex flex-wrap gap-2">{skuSelect}{date}{qty}<input aria-label="Opening SKU unit cost" name="cost" className={field} type="number" min="0" step="0.01" required placeholder="Opening unit cost"/><Button type="submit" disabled={busy}>Stage opening SKU stock</Button><p className="text-xs">Use only before cutover for a new SKU. Include this carrying value in account 1200 when importing Opening Balances. Staged stock is unavailable until the import commits.</p></form>
 <form onSubmit={submit("writeoff")} className="flex flex-wrap gap-2">{skuSelect}{date}{qty}<input aria-label="SKU write-off reason" className={field} name="reason" maxLength={300} required placeholder="Write-off reason"/><Button type="submit" disabled={busy}>Write off quantity</Button></form>
 <form onSubmit={submit("return")} className="flex flex-wrap gap-2"><select aria-label="Accessory supplier return" name="purchase" className={field} required><option value="">Choose whole purchase receipt to return</option>{purchases.map(p=><option key={p.id} value={p.id}>{p.billNumber} · {p.description} · {p.quantity}</option>)}</select>{date}<input aria-label="Supplier return reason" className={field} name="reason" maxLength={300} required placeholder="Return reason"/><Button type="submit" disabled={busy}>Return receipt to supplier</Button></form>
 <div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>SKU</th><th>Name</th><th>Quantity</th><th>Unit</th><th>Inventory value</th></tr></thead><tbody>{skus.map(s=><tr key={s.id}><td>{s.code}</td><td>{s.name}{s.isActive===false ? " (staged)" : ""}</td><td>{s.quantity}</td><td>{s.unitOfMeasure}</td><td>₹{s.inventoryValue.toFixed(2)}</td></tr>)}</tbody></table></div></section>;
}
