import type { FormFieldConfig } from "../../../types/form";

export const allControlsFormConfig: FormFieldConfig[] = [
  {
    id: "name",
    name: "name",
    label: "Full name",
    type: "text",
    required: true,
    placeholder: "Jane Doe",
  },
  {
    id: "email",
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    placeholder: "jane@company.com",
  },
  {
    id: "password",
    name: "password",
    label: "Password",
    type: "password",
    required: true,
    minLength: 8,
  },
  { id: "age", name: "age", label: "Age", type: "number", min: 18, max: 120 },
  { id: "phone", name: "phone", label: "Phone", type: "tel" },
  { id: "website", name: "website", label: "Website", type: "url" },
  {
    id: "bio",
    name: "bio",
    label: "Biography",
    type: "textarea",
    rows: 4,
    maxLength: 500,
    colSpan: 2,
  },
  {
    id: "country",
    name: "country",
    label: "Country",
    type: "select",
    required: true,
    options: [
      { label: "India", value: "in" },
      { label: "United States", value: "us" },
      { label: "United Kingdom", value: "uk" },
    ],
  },
  {
    id: "skills",
    name: "skills",
    label: "Skills",
    type: "multiSelect",
    required: true,
    maxSelections: 4,
    options: [
      { label: "React", value: "react" },
      { label: "TypeScript", value: "typescript" },
      { label: ".NET", value: "dotnet" },
      { label: "Angular", value: "angular" },
      { label: "AWS", value: "aws" },
    ],
  },
  {
    id: "employment",
    name: "employment",
    label: "Employment type",
    type: "radio",
    required: true,
    orientation: "horizontal",
    options: [
      { label: "Full time", value: "full-time" },
      { label: "Part time", value: "part-time" },
      { label: "Contract", value: "contract" },
    ],
  },
  {
    id: "notifications",
    name: "notifications",
    label: "Enable notifications",
    type: "toggle",
    defaultValue: true,
  },
  {
    id: "terms",
    name: "terms",
    label: "I accept the terms and conditions",
    type: "checkbox",
    required: true,
  },
  {
    id: "startDate",
    name: "startDate",
    label: "Start date",
    type: "date",
    required: true,
  },
  { id: "startTime", name: "startTime", label: "Start time", type: "time" },
  { id: "meeting", name: "meeting", label: "Meeting", type: "datetime" },
  {
    id: "billingMonth",
    name: "billingMonth",
    label: "Billing month",
    type: "month",
  },
  {
    id: "releaseWeek",
    name: "releaseWeek",
    label: "Release week",
    type: "week",
  },
  {
    id: "brandColor",
    name: "Brand color",
    label: "Brand color",
    type: "color",
    defaultValue: "#4f46e5",
  },
  {
    id: "priority",
    name: "priority",
    label: "Priority",
    type: "range",
    min: 0,
    max: 100,
    step: 5,
    defaultValue: 50,
  },
  {
    id: "attachment",
    name: "attachment",
    label: "Attachment",
    type: "file",
    accept: ".pdf,.doc,.docx,.png,.jpg",
    multiple: true,
    maxFiles: 3,
  },
  {
    id: "tenantId",
    name: "tenantId",
    label: "Tenant ID",
    type: "hidden",
    defaultValue: "tenant-acme-001",
  },
];
